apiVersion: apps/v1
kind: Deployment
metadata:
  name: carlo-comments
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carlo-comments
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carlo-comments
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: carlo-comments
        image: registry.digitalocean.com/carlo-containers/carlo-comments:v11
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /v1/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: PORT

        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: APP_NAME

        - name: LOG_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: LOG_DIRECTORY

        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: CORS_ALLOWED_ORIGINS

        - name: HANDLER_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: HANDLER_TIMEOUT

        - name: LIMITER_RATE
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: LIMITER_RATE

        - name: LIMITER_BURST
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: LIMITER_BURST

        - name: COMMENT_HOST
          valueFrom:
            configMapKeyRef:
              name: carlo-comments-config
              key: COMMENT_HOST

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: AWS_SECRET_ACCESS_KEY

        - name: HMAC_SECRET
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: HMAC_SECRET

        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: ADMIN_USER

        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: ADMIN_PASS

        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: S3_REGION

        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: S3_BUCKET

        - name: SES_IDENTITY
          valueFrom:
            secretKeyRef:
              name: carlo-comments-secrets
              key: SES_IDENTITY

