apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-carlo-comments
  namespace: backend
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
    # cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  tls:
    - hosts:
      - api.carlo-hamalainen.net
      secretName: letsencrypt-nginx-carlo-comments
  rules:
    - host: api.carlo-hamalainen.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carlo-comments
                port:
                  number: 80
  ingressClassName: nginx
