POST https://api.carlo-hamalainen.net/v1/admin/comments/new HTTP/1.1
content-type: application/json
Authorization: Bearer {{$processEnv ADMIN_TOKEN}}

{
  "commentID": "a9a79552-2413-454c-8262-1681d47e84f1",
  "siteID": "carlo-hamalainen.net",
  "postID": "/2024/05/30/2024-05-30-kubernetes-tls-speedrun",
  "timestamp": 1721532251424,
  "sourceAddress": "116.86.94.70",
  "author": "blah 4",
  "authorEmail": "nope@example.com",
  "commentBody": "haha\n\nyou lols\n\nthis is a comment\n\n",
  "isActive": false
}